### PR TITLE
aarch64/fenv: fix `fenv_t`

### LINKED ISSUE #278: aarch64/fenv.c:41:23: error: invalid initializer
Trying to build this for aarch64, and even tried to remove the constant to fix this, but I think I'll open an issue on this. I hope this is just me compiling this incorrectly haha

### PR DESCRIPTION
**Pull request by inkydragon**
AArch64 has two 64bit regs, AArch32 only has one.
The high 32 bits of both registers are reserved, so we only need to save the low 32 bits and pack them into a uint64.

- copy `aarch64/fenv.h` from FreeBSD
	https://github.com/freebsd/freebsd-src/blob/de1aa3dab23c06fec962a14da3e7b4755c5880cf/lib/msun/aarch64/fenv.h

Fix #278

### CODE REVIEW

**Comment by inkydragon** [comment]
OK, we also need to update all `fe*` functions.

I think it's time to move AArch64 functions into `openlibm_fenv_arm64.h` or `openlibm_fenv_aarch64.h`.

**Comment by inkydragon** [comment]
Do we want to sync `openlibm_fenv_arm.h` from FreeBSD too?

Seems there are some bugs:
https://github.com/JuliaMath/openlibm/blob/5a88ede059eab2c651a3c1589aabe85136ea9a48/include/openlibm_fenv_arm.h#L65-L67

```c
/* We need to be able to map status flag positions to mask flag positions */
#ifndef __ARM_PCS_VFP
#define	_FPUSW_SHIFT	16
#define	_ENABLE_MASK	(FE_ALL_EXCEPT << _FPUSW_SHIFT)
#endif
```
https://github.com/freebsd/freebsd-src/blob/de1aa3dab23c06fec962a14da3e7b4755c5880cf/lib/msun/arm/fenv.h#L83-L87

```c
#else	/* __ARM_PCS_VFP */

...

#define _FPU_MASK_SHIFT	8
```
https://github.com/freebsd/freebsd-src/blob/de1aa3dab23c06fec962a14da3e7b4755c5880cf/lib/msun/arm/fenv.h#L113

File: include/openlibm_fenv_aarch64.h [hunk 1]
```diff
@@ -0,0 +1,247 @@
...
+/* Default floating-point environment */
+extern const fenv_t	__fe_dfl_env;
+#define	FE_DFL_ENV	(&__fe_dfl_env)
+
+/* We need to be able to map status flag positions to mask flag positions */
+#define _FPUSW_SHIFT	8
+#define	_ENABLE_MASK	(FE_ALL_EXCEPT << _FPUSW_SHIFT)
+
+#define	__mrs_fpcr(__r)	__asm __volatile("mrs %0, fpcr" : "=r" (__r))
+#define	__msr_fpcr(__r)	__asm __volatile("msr fpcr, %0" : : "r" (__r))
```
Comment (inkydragon) [inline include/openlibm_fenv_aarch64.h:76]: I'd like to rename those functions to `__read_fpcr`, `__write_fpcr`.
Or `reg_fpcr_read()`, `reg_fpsr_write()` (NetBSD style)

**Comment by ViralBShah** [comment]
Please merge if ready.

**Comment by inkydragon** [comment]
All CI passed. Assume everything works well.

**Comment by lazka** [comment]
This fails to build on Windows, any ideas?

```
clang  -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -Wp,-D__USE_MINGW_ANSI_STDIO=1 -fno-builtin -fno-strict-aliasing  -std=c99 -Wall -I/c/M/B/src/build-CLANGARM64 -I/c/M/B/src/build-CLANGARM64/include -I/c/M/B/src/build-CLANGARM64/aarch64 -I/c/M/B/src/build-CLANGARM64/src -DASSEMBLER -D__BSD_VISIBLE -Wno-implicit-function-declaration -I/c/M/B/src/build-CLANGARM64/ld128 -c src/s_fma.c -o src/s_fma.c.o
In file included from src/s_fma.c:31:
In file included from C:/M/B/src/build-CLANGARM64/include/openlibm_fenv.h:6:
C:/M/B/src/build-CLANGARM64/include/openlibm_fenv_aarch64.h:39:9: error: unknown type name '__uint64_t'; did you mean 'uint64_t'?
   39 | typedef __uint64_t      fenv_t;
      |         ^~~~~~~~~~
      |         uint64_t
```

**Comment by jeremyd2019** [comment]
it looks like other arches' headers (`openlibm_fenv_{arm,amd64}.h` at least) use the standard non-double-underscore names for these types.

**Comment by lazka** [comment]
yeah, that seems to have done the trick: https://github.com/msys2/MINGW-packages/blob/356bd84ad0398d2e063448ad7689fa5f04d7a00c/mingw-w64-openlibm/0002-fix-aarch64-build.patch
